use_frameworks!

platform :ios, '8.0'

target 'WGDropDownMenu_Example' do
  pod 'WGDropDownMenu', :path => '../'

  target 'WGDropDownMenu_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
